### PR TITLE
Embed updates

### PR DESCRIPTION
**Pull request by BenSegal855**
## Describe this PR and why it should be merged
This PR makes several changes improving embeds displayed through out the bot.
### EmbedColor enum
An EmbedColor enum was added to make it easier to get the same color consistently across multiple embeds.
### Page-ated reminders
Taking advantage of Klasa's Rich Embed feature, `prefix reminder view` will now show chunks of five reminders. It also shows info on how to cancel a reminder. Do note that this required using the github url for the clock thumbnail as it seams Rich embeds cannot utlize attachments.
### Other changes
- The stats command's embed was updated so fields are now inline. This makes the overall message take up less space.
- I added `whoami` as an alias to `whois`

## Status
- [X] This PR has been tested and complies with this project's ESLint rules
- [X] This PR adds/modifes a command

## Semantic Versioning
- [ ] This PR features bug fixes, or only style changes/refactorings, or no code changes
- [ ] This PR adds features for users
- [ ] This PR switches this project to a new a new Discord API library/new Discord.js framework

### CODE REVIEW

**Comment by jwford** [comment]
will take a closer look at this later after work, but the stats fields aren't inline on purpose, it looked kinda wonky when i did that and even when they're not inline the embed isn't too big

**Comment by jwford** [comment]
as far as attachments in rich displays, did you use the `.attachFiles()` method?

**Comment by BenSegal855** [comment]
> will take a closer look at this later after work, but the stats fields aren't inline on purpose, it looked kinda wonky when i did that and even when they're not inline the embed isn't too big

I run my client at 150% scale so for me it takes up a lot of space but you are right, with inline fields it does look a bit wonky. I wonder if there is some way to make it not as tall but also not wonky looking.

> as far as attachments in rich displays, did you use the `.attachFiles()` method?

I originally kept the same code using `.attachFiles(['./assets/images/alarmclock.png'])` then `setThumbnail('attachment://alarmclock.png')` and the embed would load with no errors but the thumbnail would not be there. Changing that to be just `.setThumbnail('https://github.com/tuataria/steve/blob/master/assets/images/alarmclock.png?raw=true')` caused the thumbnail to show.

**Comment by BenSegal855** [comment]
Closeting because most stuff was implemented in the codebase or in #65

**Pull request closed without merging**
